/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expenseManager.View;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import expenseManager.Model.ClearInputs;
import expenseManager.Model.Energy;
import expenseManager.Model.Expense;
import expenseManager.Model.Product;
import expenseManager.Model.PutEnergy;
import expenseManager.Model.PutProduct;
import expenseManager.Model.PutService;
import expenseManager.Model.SelectedEnergy;
import expenseManager.Model.SelectedProduct;
import expenseManager.Model.SelectedService;
import expenseManager.Model.Service;

/**
 *
 * @author alamtrindade
 */
public class PutExpenses extends javax.swing.JFrame {
    
    /**
     * Creates new form PutExpenses
     */
    
    ArrayList<Expense> expenses;
    private String directory;
    
    public PutExpenses(ArrayList<Expense> expenses, String directory) {
        initComponents();
        this.expenses = expenses;
        this.directory = directory;
        new SelectedService().serviceSelected(jDate, jCNPJ, jDescription, jQtd, jValue);
        this.rServices.setSelected(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeExpense = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rServices = new javax.swing.JRadioButton();
        rProducts = new javax.swing.JRadioButton();
        rEnergy = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDescription = new javax.swing.JTextField();
        jQtd = new javax.swing.JTextField();
        jValue = new javax.swing.JTextField();
        jDate = new javax.swing.JFormattedTextField();
        jCNPJ = new javax.swing.JFormattedTextField();
        bExit = new javax.swing.JButton();
        bPut = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Tipo de Despesa");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        typeExpense.add(rServices);
        rServices.setText("Serviços");
        rServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rServicesActionPerformed(evt);
            }
        });

        typeExpense.add(rProducts);
        rProducts.setText("Produtos");
        rProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProductsActionPerformed(evt);
            }
        });

        typeExpense.add(rEnergy);
        rEnergy.setText("Energia Elétrica");
        rEnergy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEnergyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rServices)
                .addGap(69, 69, 69)
                .addComponent(rProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(rEnergy)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rServices)
                    .addComponent(rProducts)
                    .addComponent(rEnergy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Dados da Despesa");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setText("Data:");

        jLabel5.setText("CNPJ:");

        jLabel6.setText("Descrição:");

        jLabel7.setText("Qtd:");

        jLabel8.setText("Valor:");

        jDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDescriptionActionPerformed(evt);
            }
        });

        try {
            jDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDescription)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(jQtd, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCNPJ))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bExit.setText("Cancelar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bPut.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bPut.setText("Lançar");
        bPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPut)
                    .addComponent(bExit))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rServicesActionPerformed
        // TODO add your handling code here:
        new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
        new SelectedService().serviceSelected(jDate, jCNPJ, jDescription, jQtd, jValue);
    }//GEN-LAST:event_rServicesActionPerformed

    private void rEnergyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEnergyActionPerformed
        // TODO add your handling code here:
        new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
        new SelectedEnergy().EnergySelected(jDate, jCNPJ, jDescription, jQtd, jValue);
    }//GEN-LAST:event_rEnergyActionPerformed

    private void jDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDescriptionActionPerformed

    private void bPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPutActionPerformed
        // TODO add your handling code here:
        if(this.rServices.isSelected() == true){
            
            try {
                
                Service service = new Service(jDate.getText(), Double.parseDouble(jValue.getText()), jCNPJ.getText(), jDescription.getText());
               
                new PutService().putService(this.expenses, service, this.directory);
                
            } catch (ParseException ex) {
                Logger.getLogger(PutExpenses.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            int i = JOptionPane.showConfirmDialog(null ,"Deseja Lançar Uma Nova Despesa?","Saída",JOptionPane.YES_NO_OPTION);
            
            if(i == JOptionPane.YES_OPTION ){
                new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
            }else{
                this.dispose();
            }        
            
           
        }else if(this.rProducts.isSelected() == true){
            try {
                
                Product product = new Product(jDate.getText(), jDescription.getText(), Integer.parseInt(jQtd.getText()), Integer.parseInt(jQtd.getText())* Double.parseDouble(jValue.getText()));
                new PutProduct().putProduct(this.expenses, product, this.directory);
                
            } catch (ParseException ex) {
                Logger.getLogger(PutExpenses.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            int i = JOptionPane.showConfirmDialog(null ,"Deseja Lançar Uma Nova Despesa?","Saída",JOptionPane.YES_NO_OPTION);
            
            if(i == JOptionPane.YES_OPTION ){
                new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
            }else{
                this.dispose();
            }  
           
        }else{
            try {
                
                Energy energy = new Energy(jDate.getText(),Double.parseDouble(jValue.getText()));
                new PutEnergy().putEnergy(this.expenses, energy, this.directory);
                
            } catch (ParseException ex) {
                Logger.getLogger(PutExpenses.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            int i = JOptionPane.showConfirmDialog(null ,"Deseja Lançar Uma Nova Despesa?","Saída",JOptionPane.YES_NO_OPTION);
            
            if(i == JOptionPane.YES_OPTION ){
                new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
            }else{
                this.dispose();
            }  
            
        }
    }//GEN-LAST:event_bPutActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void rProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProductsActionPerformed
        // TODO add your handling code here:
        new ClearInputs().clear(jDate, jCNPJ, jDescription, jQtd, jValue);
        new SelectedProduct().productSelected(jDate, jCNPJ, jDescription, jQtd, jValue);
    }//GEN-LAST:event_rProductsActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bPut;
    private javax.swing.JFormattedTextField jCNPJ;
    private javax.swing.JFormattedTextField jDate;
    private javax.swing.JTextField jDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jQtd;
    private javax.swing.JTextField jValue;
    private javax.swing.JRadioButton rEnergy;
    private javax.swing.JRadioButton rProducts;
    private javax.swing.JRadioButton rServices;
    private javax.swing.ButtonGroup typeExpense;
    // End of variables declaration//GEN-END:variables
}
